### ISSUE TITLE
Implement the weekly goal modal

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot-sauce#10]
Need to implement the encouragement modal. This is will be for display only, the logic for this will be implement in the future.

<img width="1272" alt="Screen Shot 2021-12-15 at 7 07 02 AM" src="https://user-images.githubusercontent.com/5713670/146211572-6857a261-021d-478a-aad1-502b12ce2ec5.png">
 
Link to elements:
1. [Code](https://github.com/bdougie/hot-open-sauced/blob/main/components/layout/Modal.jsx)
2. [Live App](https://hot-open-sauced.vercel.app/)

**Comment by JScrips** [comment]
this PR closes this issue: https://github.com/open-sauced/hot-sauce/pull/13
