### ISSUE TITLE
Feature:Add font-awesome icons 

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot-sauce#15]
### Type of feature

Feature

### Current behavior

Some components were added without font-awesome
![Screen Shot 2021-12-17 at 3 43 43 PM](https://user-images.githubusercontent.com/5713670/146605554-d3aa1a2b-ca09-441d-b5f8-c39e79baf1dd.png)
![Screen Shot 2021-12-17 at 3 43 39 PM](https://user-images.githubusercontent.com/5713670/146605555-e0e18181-f7da-479c-9ee1-8f2a893ecac1.png)
![Screen Shot 2021-12-17 at 3 43 36 PM](https://user-images.githubusercontent.com/5713670/146605556-ba356536-59c2-4bbc-804f-cad20a865e20.png)

### Desired solution

![Screen Shot 2021-12-17 at 3 45 01 PM](https://user-images.githubusercontent.com/5713670/146605692-f1dd97c5-3f13-4d6b-9f58-3d1c41ec92f7.png)
![Screen Shot 2021-12-17 at 3 44 58 PM](https://user-images.githubusercontent.com/5713670/146605693-99cf3fd6-aeb2-4338-b157-7f38b78a4e0f.png)
![Screen Shot 2021-12-17 at 3 44 55 PM](https://user-images.githubusercontent.com/5713670/146605694-e2c7fe6f-b18d-4fd4-9537-6df58dae3cfd.png)

### Additional context

The PR #13 introduce these components but did not introduce the font icons

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kelvinsekx** [comment]
.take
