### ISSUE TITLE
Enable Tailwind in this project

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot-sauce#5]
Tailwind needs to be accessible to this project. 

https://daily-dev-tips.com/posts/how-to-use-tailwind-css-in-astro/

```
npm install -D tailwindcss
```

there are some follow up config files needed.

```js
// tailwind.config.js

module.exports = {
  mode: 'jit',
  purge: ['./public/**/*.html', './src/**/*.{astro,js,jsx,ts,tsx,vue}'],
};
```

```js
// astro.config.js
devOptions: {
  tailwindConfig: './tailwind.config.js';
}
```

```css
// global.css 

@tailwind base;
@tailwind components;
@tailwind utilities;
```

**Comment by NaaLaryea** [comment]
Hello @bdougie I would like to pick this up and work on it.

**Comment by kelvinsekx** [comment]
Ok...I think I should drop it on my side then. 
I was already working on it...Is that fine @NaaLaryea ?

**Comment by NaaLaryea** [comment]
Yes that is fine. Thank you for understanding, and apologies on the conflict

**Comment by kelvinsekx** [comment]
No qualms...
Although, I have implemented it on my local side anyways.

**Comment by bdougie** [comment]
You should be able to rebase on your end @kelvinsekx. The solution will look the same at the end of the day.

**Comment by NaaLaryea** [comment]
.take

**Comment by kelvinsekx** [comment]
Generally, I particularly find this link, https://benborgers.com/posts/astro-tailwind,  cleaner with less typos.
Also when you encounter multiple problems for example
- TypeError: Expected a `string`, got `undefined`...strpAnsi
- or path-regexp not found, etc

You first correct the tailwindConfig file: move the moduleResolution into compilerOptions object

```
{
  "compilerOptions": {
    "moduleResolution": "node"
  }
}
```

Then if your tailwind don't work yet? ...You need to do it the Astro way. This link would help, https://docs.astro.build/guides/styling/#-tailwind.

```
// postcss.config.cjs
module.exports = {
  plugins: [require("tailwindcss")],
};
```

I hope you find this useful

**Comment by JScrips** [comment]
this PR closes this issue: https://github.com/open-sauced/hot-sauce/pull/13

**Comment by NaaLaryea** [comment]
Hello, so i was working on this, as stated earlier in the comments. @bdougie do i pick something else up then?

**Comment by bdougie** [comment]
I messaged @JScrips on this. Best practiced is announcing intentions on the issue first, but considering this is needed to do any other issue, I think we will need to go with his PR.

**Comment by kelvinsekx** [comment]
Okay that's fine. I was waiting on @NaaLaryea to add the tailwind config too before putting up my stuffs. But I guess things are on a different level now.
