### ISSUE TITLE
Create Repo card components

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot-sauce#6]
## Today the site content looks like this when displaying GitHub repos. 

![Screen Shot 2021-12-15 at 6 58 30 AM](https://user-images.githubusercontent.com/5713670/146209960-794fdc52-dbf1-4fe2-8e6c-5a90e13fbf79.png)

## What we would like it to look like 

![Screen Shot 2021-12-15 at 6 55 01 AM](https://user-images.githubusercontent.com/5713670/146210051-4b5d1997-6c01-4bb8-995c-8868ecf08748.png)

Steps to implement:

1. Apply Tailwind UI to a reusable React component
2. Add the component to the render repo

Link to CSS: 

1. [PostGrid](https://github.com/bdougie/hot-open-sauced/blob/main/components/post/PostGrid.jsx)

**Comment by kelvinsekx** [comment]
.take

**Comment by JScrips** [comment]
this PR closes this issue: https://github.com/open-sauced/hot-sauce/pull/13
