### ISSUE TITLE
Create PostList components

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot-sauce#7]
## Today the site content looks like this when displaying GitHub repos. 

![Screen Shot 2021-12-15 at 6 58 30 AM](https://user-images.githubusercontent.com/5713670/146209960-794fdc52-dbf1-4fe2-8e6c-5a90e13fbf79.png)

## What we would like it to look like 

![Screen Shot 2021-12-15 at 7 00 19 AM](https://user-images.githubusercontent.com/5713670/146210292-c53b15d2-6341-4252-a6e3-32946acf4caf.png)

Steps to implement:

1. Apply Tailwind UI to a reusable React component
2. Add the component to the render repo

Link to CSS: 

1. [PostList](https://github.com/bdougie/hot-open-sauced/blob/main/components/post/PostList.jsx)

**Comment by JScrips** [comment]
this PR closes this issue: https://github.com/open-sauced/hot-sauce/pull/13
