### ISSUE TITLE
PostList and PostGrid toggle and nav bar

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot-sauce#8]
Looking to implement a toggle for the PostList and PostGrid display. 
![Screen Shot 2021-12-15 at 7 00 19 AM](https://user-images.githubusercontent.com/5713670/146210721-b360385f-1cb6-42fe-8a6a-58132555a105.png)

This issue is dependent on #6 and #7 being complement before being started

Link to it working in the Next app:
1. [Code](https://github.com/bdougie/hot-open-sauced/blob/main/components/layout/LayoutToggle.jsx)
2. [Live](https://hot-open-sauced.vercel.app/) 

https://user-images.githubusercontent.com/5713670/146210870-41f27549-03a9-47ff-b886-6fa89463d75f.mp4

**Comment by kelvinsekx** [comment]
.take

**Comment by kelvinsekx** [comment]
.take

**Comment by JScrips** [comment]
this PR closes this issue: https://github.com/open-sauced/hot-sauce/pull/13
