### ISSUE TITLE
Add navigation/filter

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot-sauce#9]
Navigation and filter submenu needs to be implemented on the page. 
<img width="1277" alt="Screen Shot 2021-12-15 at 7 05 26 AM" src="https://user-images.githubusercontent.com/5713670/146211175-26116ed6-da81-4810-8e72-8eeffd90b875.png">

All CSS and elements can be found in the example Next App.

1. [Code](https://github.com/bdougie/hot-open-sauced/tree/main/components/layout)
2. [Live site](https://hot-open-sauced.vercel.app/)

**Comment by kelvinsekx** [comment]
@bdougie I would pick this.

**Comment by bdougie** [comment]
Please review the [CONTIBUTING.md](https://github.com/open-sauced/.github/blob/HEAD/CONTRIBUTING.md) for info on how to assign yourself to the issue.

**Comment by JScrips** [comment]
this PR closes this issue: https://github.com/open-sauced/hot-sauce/pull/13
